name: Metrics
on:
  schedule: [{cron: "45 4 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: gh-metrics/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: BXZ1
          template: classic
          base: ""
          config_display: large
          config_timezone: Africa/Algiers
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 5
          plugin_lines_repositories_limit: 5
          plugin_lines_sections: base
          plugin_stars: yes
          plugin_stars_limit: 4
          repositories_forks: yes
          users_ignored: 
